services:
  - type: web
    name: wqms-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT --chdir backend wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: API_HOST
        value: "0.0.0.0"
